refine create-final-bosh-release-on-commits.yml to skip releases with no blob changes

diff --git a/.github/workflows/create-final-bosh-release-on-commits.yml b/.github/workflows/create-final-bosh-release-on-commits.yml
--- a/.github/workflows/create-final-bosh-release-on-commits.yml
+++ b/.github/workflows/create-final-bosh-release-on-commits.yml
@@ -14,7 +14,7 @@ on:
       - jobs/**
       - releases/**
       - vendir.yml
-      - .github/workflows/on-commits.yml
+      - .github/workflows/create-final-bosh-release-on-commits.yml
 
 jobs:
   build:
@@ -132,7 +132,7 @@ jobs:
             yq -r "{ \"builds\": (.builds | with_entries(select(.value.version != \"${version}\"))), \"format-version\": .[\"format-version\"]}" < releases/${name}/index.yml > tmp
             mv tmp releases/${name}/index.yml
             rm -f releases/${name}/${name}-${version}.yml
-            git commit -a -m "reset release ${version}"
+            git add releases/${name}/${name}-${version}.yml releases/${name}/index.yml 
           fi
           
           echo "Current AWS config"
@@ -142,22 +142,32 @@ jobs:
           echo "creating bosh release: ${name}-${version}.tgz"
           bosh create-release --final --version=${version} --tarball=${name}-${version}.tgz
           
-          echo "pushing changes to git repository"
           git add .final_builds
           git add releases/${name}/index.yml
-          git add releases/${name}/${name}-${version}.yml
-          git commit -a -m "cutting release ${version}"
+          RELEASE_FILE_NAME=releases/${name}/${name}-${version}.yml
+          git add ${RELEASE_FILE_NAME}
           
-          # Override any existing tag with same version. This may happen if only part of the renovate PRs were merged
-          git tag -a -m "cutting release ${version}" ${version} -f
-          git pull --rebase ${remote_repo} ${GITHUB_REF_NAME}
-          git push ${remote_repo} HEAD:${INPUT_TARGET_BRANCH}
-          
-          # Delete any existing release with same tag. Ignore push failure if no tag exists.
-          ! git push --delete ${remote_repo} ${version}
-          
-          # Push the tag
-          git push ${remote_repo} ${version} --force
+          # Detect if the
+          echo "Inspecting staged files to skip commit and push if there is no blob changes in the release 
+          if ! git diff --cached ${RELEASE_FILE_NAME} | grep sha1 then
+            echo "No sha1 found in diff in ${RELEASE_FILE_NAME}. No blob were modified. Skip the release"
+            ls -al ${RELEASE_FILE_NAME}
+            cat ${RELEASE_FILE_NAME}
+          else
+            git commit -a -m "cutting release ${version}"
+            echo "pushing changes to git repository"
+            
+            # Override any existing tag with same version. This may happen if only part of the renovate PRs were merged
+            git tag -a -m "cutting release ${version}" ${version} -f
+            git pull --rebase ${remote_repo} ${GITHUB_REF_NAME}
+            git push ${remote_repo} HEAD:${INPUT_TARGET_BRANCH}
+            
+            # Delete any existing release with same tag. Ignore push failure if no tag exists.
+            ! git push --delete ${remote_repo} ${version}
+            
+            # Push the tag
+            git push ${remote_repo} ${version} --force
+          fi
           
           # make asset readable outside docker image
           chmod 644 ${name}-${version}.tgz
